### Data cleaning:

* missing data [replace,dropna,fillna]
* fill the missing values using scikit-learn
* duplicate data

In [1]:
import pandas as pd
import numpy as np

In [23]:
a=np.array([[1,2,np.nan,3,4],
           [10,12,13,14,15],
           [67,34,29,70,55],
           [np.nan,10,23,np.nan,34],
           [67,np.nan,31,54,np.nan],
           [90,np.nan,np.nan,45,np.nan]]
          )
a

array([[ 1.,  2., nan,  3.,  4.],
       [10., 12., 13., 14., 15.],
       [67., 34., 29., 70., 55.],
       [nan, 10., 23., nan, 34.],
       [67., nan, 31., 54., nan],
       [90., nan, nan, 45., nan]])

In [24]:
df=pd.DataFrame(a,columns=["one","two","three","four","five"])
df

one   two  three  four  five
0   1.0   2.0    NaN   3.0   4.0
1  10.0  12.0   13.0  14.0  15.0
2  67.0  34.0   29.0  70.0  55.0
3   NaN  10.0   23.0   NaN  34.0
4  67.0   NaN   31.0  54.0   NaN
5  90.0   NaN    NaN  45.0   NaN

In [25]:
df.isnull().sum()

one      1
two      2
three    2
four     1
five     2
dtype: int64

In [26]:
df[df.isnull().any(axis=1)]

one   two  three  four  five
0   1.0   2.0    NaN   3.0   4.0
3   NaN  10.0   23.0   NaN  34.0
4  67.0   NaN   31.0  54.0   NaN
5  90.0   NaN    NaN  45.0   NaN

In [27]:
# we can handle nan value using two ways
# dropna
# fillna

df.dropna()

one   two  three  four  five
1  10.0  12.0   13.0  14.0  15.0
2  67.0  34.0   29.0  70.0  55.0

In [28]:
df['one']=df['one'].replace(np.nan,0)

In [29]:
df

one   two  three  four  five
0   1.0   2.0    NaN   3.0   4.0
1  10.0  12.0   13.0  14.0  15.0
2  67.0  34.0   29.0  70.0  55.0
3   0.0  10.0   23.0   NaN  34.0
4  67.0   NaN   31.0  54.0   NaN
5  90.0   NaN    NaN  45.0   NaN

In [30]:
df['two'].mean()

14.5

In [31]:
df['two']=df['two'].fillna(df['two'].mean())

In [32]:
df

one   two  three  four  five
0   1.0   2.0    NaN   3.0   4.0
1  10.0  12.0   13.0  14.0  15.0
2  67.0  34.0   29.0  70.0  55.0
3   0.0  10.0   23.0   NaN  34.0
4  67.0  14.5   31.0  54.0   NaN
5  90.0  14.5    NaN  45.0   NaN

In [33]:
df['three']=df['three'].fillna(df['three'].median())

In [34]:
df

one   two  three  four  five
0   1.0   2.0   26.0   3.0   4.0
1  10.0  12.0   13.0  14.0  15.0
2  67.0  34.0   29.0  70.0  55.0
3   0.0  10.0   23.0   NaN  34.0
4  67.0  14.5   31.0  54.0   NaN
5  90.0  14.5   26.0  45.0   NaN

In [19]:
df.fillna(method='ffill')

one   two  three  four  five
0   1.0   2.0   26.0   3.0   4.0
1  10.0  12.0   13.0  14.0  15.0
2  67.0  34.0   29.0  70.0  55.0
3   0.0  10.0   23.0  70.0  34.0
4  67.0  14.5   31.0  54.0  34.0
5  90.0  14.5   26.0  45.0  89.0

In [20]:
df.fillna(method='bfill')

one   two  three  four  five
0   1.0   2.0   26.0   3.0   4.0
1  10.0  12.0   13.0  14.0  15.0
2  67.0  34.0   29.0  70.0  55.0
3   0.0  10.0   23.0  54.0  34.0
4  67.0  14.5   31.0  54.0  89.0
5  90.0  14.5   26.0  45.0  89.0

In [21]:
df

one   two  three  four  five
0   1.0   2.0   26.0   3.0   4.0
1  10.0  12.0   13.0  14.0  15.0
2  67.0  34.0   29.0  70.0  55.0
3   0.0  10.0   23.0   NaN  34.0
4  67.0  14.5   31.0  54.0   NaN
5  90.0  14.5   26.0  45.0  89.0

In [22]:
df.fillna(method='ffill',limit=1)

one   two  three  four  five
0   1.0   2.0   26.0   3.0   4.0
1  10.0  12.0   13.0  14.0  15.0
2  67.0  34.0   29.0  70.0  55.0
3   0.0  10.0   23.0  70.0  34.0
4  67.0  14.5   31.0  54.0  34.0
5  90.0  14.5   26.0  45.0  89.0

In [35]:
df

one   two  three  four  five
0   1.0   2.0   26.0   3.0   4.0
1  10.0  12.0   13.0  14.0  15.0
2  67.0  34.0   29.0  70.0  55.0
3   0.0  10.0   23.0   NaN  34.0
4  67.0  14.5   31.0  54.0   NaN
5  90.0  14.5   26.0  45.0   NaN

In [37]:
df.fillna(method='ffill',limit=2)

one   two  three  four  five
0   1.0   2.0   26.0   3.0   4.0
1  10.0  12.0   13.0  14.0  15.0
2  67.0  34.0   29.0  70.0  55.0
3   0.0  10.0   23.0  70.0  34.0
4  67.0  14.5   31.0  54.0  34.0
5  90.0  14.5   26.0  45.0  34.0

### How to fill the missing values using sckit-learn

In [38]:
a=np.array([[1,2,np.nan,3,4],
           [10,12,13,14,15],
           [67,34,29,70,55],
           [np.nan,10,23,np.nan,34],
           [67,np.nan,31,54,np.nan],
           [90,np.nan,np.nan,45,np.nan]]
          )
a

array([[ 1.,  2., nan,  3.,  4.],
       [10., 12., 13., 14., 15.],
       [67., 34., 29., 70., 55.],
       [nan, 10., 23., nan, 34.],
       [67., nan, 31., 54., nan],
       [90., nan, nan, 45., nan]])

In [39]:
df=pd.DataFrame(a,columns=["one","two","three","four","five"])
df

one   two  three  four  five
0   1.0   2.0    NaN   3.0   4.0
1  10.0  12.0   13.0  14.0  15.0
2  67.0  34.0   29.0  70.0  55.0
3   NaN  10.0   23.0   NaN  34.0
4  67.0   NaN   31.0  54.0   NaN
5  90.0   NaN    NaN  45.0   NaN

In [42]:
from sklearn.impute import SimpleImputer
s=SimpleImputer(strategy='mean')
filldata=s.fit_transform(df)
filldata

array([[ 1. ,  2. , 24. ,  3. ,  4. ],
       [10. , 12. , 13. , 14. , 15. ],
       [67. , 34. , 29. , 70. , 55. ],
       [47. , 10. , 23. , 37.2, 34. ],
       [67. , 14.5, 31. , 54. , 27. ],
       [90. , 14.5, 24. , 45. , 27. ]])

In [43]:
missing_df_mean=pd.DataFrame(filldata,columns=df.columns)
missing_df_mean

one   two  three  four  five
0   1.0   2.0   24.0   3.0   4.0
1  10.0  12.0   13.0  14.0  15.0
2  67.0  34.0   29.0  70.0  55.0
3  47.0  10.0   23.0  37.2  34.0
4  67.0  14.5   31.0  54.0  27.0
5  90.0  14.5   24.0  45.0  27.0

In [44]:
# median
from sklearn.impute import SimpleImputer
s=SimpleImputer(strategy='median')
filldata=s.fit_transform(df)
filldata

array([[ 1. ,  2. , 26. ,  3. ,  4. ],
       [10. , 12. , 13. , 14. , 15. ],
       [67. , 34. , 29. , 70. , 55. ],
       [67. , 10. , 23. , 45. , 34. ],
       [67. , 11. , 31. , 54. , 24.5],
       [90. , 11. , 26. , 45. , 24.5]])

In [45]:
# most-frequent
from sklearn.impute import SimpleImputer
s=SimpleImputer(strategy='most_frequent')
filldata=s.fit_transform(df)
filldata

array([[ 1.,  2., 13.,  3.,  4.],
       [10., 12., 13., 14., 15.],
       [67., 34., 29., 70., 55.],
       [67., 10., 23.,  3., 34.],
       [67.,  2., 31., 54.,  4.],
       [90.,  2., 13., 45.,  4.]])

In [46]:
df_most_fre=pd.DataFrame(filldata,columns=df.columns)
df_most_fre

one   two  three  four  five
0   1.0   2.0   13.0   3.0   4.0
1  10.0  12.0   13.0  14.0  15.0
2  67.0  34.0   29.0  70.0  55.0
3  67.0  10.0   23.0   3.0  34.0
4  67.0   2.0   31.0  54.0   4.0
5  90.0   2.0   13.0  45.0   4.0

In [47]:
# constant
from sklearn.impute import SimpleImputer
s=SimpleImputer(strategy='constant',fill_value=0)
filldata=s.fit_transform(df)
filldata

array([[ 1.,  2.,  0.,  3.,  4.],
       [10., 12., 13., 14., 15.],
       [67., 34., 29., 70., 55.],
       [ 0., 10., 23.,  0., 34.],
       [67.,  0., 31., 54.,  0.],
       [90.,  0.,  0., 45.,  0.]])

### drop duplicates

In [52]:
df=pd.DataFrame({'sno':[110,101,101,102,102,103,104,105,110],
                'sname':["e",'a','a','b','b','c','d','f','e']})
df

sno sname
0  110     e
1  101     a
2  101     a
3  102     b
4  102     b
5  103     c
6  104     d
7  105     f
8  110     e

In [53]:
df.duplicated()

0    False
1    False
2     True
3    False
4     True
5    False
6    False
7    False
8     True
dtype: bool

In [54]:
df[df.duplicated()]

sno sname
2  101     a
4  102     b
8  110     e

In [55]:
#df.duplicated(subset,keep)
df.duplicated('sno')

0    False
1    False
2     True
3    False
4     True
5    False
6    False
7    False
8     True
dtype: bool

In [59]:
df.duplicated(keep='first')

0    False
1    False
2     True
3    False
4     True
5    False
6    False
7    False
8     True
dtype: bool

In [60]:
df.duplicated(keep='last')

0     True
1     True
2    False
3     True
4    False
5    False
6    False
7    False
8    False
dtype: bool

In [61]:
df.duplicated(keep=False)

0     True
1     True
2     True
3     True
4     True
5    False
6    False
7    False
8     True
dtype: bool

In [62]:
df[df.duplicated(keep=False)]

sno sname
0  110     e
1  101     a
2  101     a
3  102     b
4  102     b
8  110     e

In [66]:
df.drop_duplicates(inplace=True)

In [67]:
df

sno sname
0  110     e
1  101     a
3  102     b
5  103     c
6  104     d
7  105     f

### Task:cars.csv

* replace the ? with nan values
* find the sum of nan values
* fill the nan values using mean or median
* In make feature(column) we have data with (-), ex: alfa-romero. so, keep the before character of (-) in make feature i.e alfa

In [68]:
import pandas as pd
import numpy as np

In [70]:
df=pd.read_csv("cars.csv")
df.head()

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two   
1          3                 ?  alfa-romero       gas        std          two   
2          1                 ?  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19     3.4              10.0        102      5500       24   
4         mpfi  3.19     3.4               8.0        115      5500       18   

  highway-mpg  price  
0          27  13495  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  

[5 rows x 26 columns]

In [71]:
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [74]:
df.isnull().any(axis=1).sum()

0

In [75]:
df=df.replace('?',np.nan)

In [77]:
df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [78]:
df.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [79]:
#df['normalized-losses']=df['normalized-losses'].fillna(df['normalized-losses'].mean())

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [81]:
df.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [82]:
df["normalized-losses"]=df.replace("mean")

In [83]:
df.head()

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 3  alfa-romero       gas        std          two   
1          3                 3  alfa-romero       gas        std          two   
2          1                 1  alfa-romero       gas        std          two   
3          2                 2         audi       gas        std         four   
4          2                 2         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19     3.4              10.0        102      5500       24   
4         mpfi  3.19     3.4               8.0        115      5500       18   

  highway-mpg  price  
0          27  13495  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  

[5 rows x 26 columns]

In [84]:
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         2
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 4
stroke               4
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                4
dtype: int64

In [87]:
df['price']=pd.to_numeric(df['price'])

In [89]:
df['price']=df['price'].fillna(df['price'].mean())

In [90]:
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         2
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 4
stroke               4
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [91]:
df.head()

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 3  alfa-romero       gas        std          two   
1          3                 3  alfa-romero       gas        std          two   
2          1                 1  alfa-romero       gas        std          two   
3          2                 2         audi       gas        std         four   
4          2                 2         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19     3.4              10.0        102      5500       24   
4         mpfi  3.19     3.4               8.0        115      5500       18   

  highway-mpg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [92]:
df['make']

0      alfa-romero
1      alfa-romero
2      alfa-romero
3             audi
4             audi
5             audi
6             audi
7             audi
8             audi
9             audi
10             bmw
11             bmw
12             bmw
13             bmw
14             bmw
15             bmw
16             bmw
17             bmw
18       chevrolet
19       chevrolet
20       chevrolet
21           dodge
22           dodge
23           dodge
24           dodge
25           dodge
26           dodge
27           dodge
28           dodge
29           dodge
          ...     
175         toyota
176         toyota
177         toyota
178         toyota
179         toyota
180         toyota
181         toyota
182     volkswagen
183     volkswagen
184     volkswagen
185     volkswagen
186     volkswagen
187     volkswagen
188     volkswagen
189     volkswagen
190     volkswagen
191     volkswagen
192     volkswagen
193     volkswagen
194          volvo
195          volvo
196         

In [94]:
df.sample(10)

symboling normalized-losses           make fuel-type aspiration  \
93           1                 1         nissan       gas        std   
176         -1                -1         toyota       gas        std   
193          0                 0     volkswagen       gas        std   
73           0                 0  mercedes-benz       gas        std   
149          0                 0         subaru       gas      turbo   
188          2                 2     volkswagen       gas        std   
140          2                 2         subaru       gas        std   
162          0                 0         toyota       gas        std   
132          3                 3           saab       gas        std   
101          0                 0         nissan       gas        std   

    num-of-doors body-style drive-wheels engine-location  wheel-base  ...  \
93          four      wagon          fwd           front        94.5  ...   
176         four      sedan          fwd           front       102.4  ...   
193         four      wagon          fwd           front       100.4  ...   
73          four      sedan          rwd           front       120.9  ...   
149         four      wagon          4wd           front        96.9  ...   
188         four      sedan          fwd           front        97.3  ...   
140          two  hatchback          4wd           front        93.3  ...   
162         four      sedan          fwd           front        95.7  ...   
132          two  hatchback          fwd           front        99.1  ...   
101         four      sedan          fwd           front       100.4  ...   

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
93            97         2bbl  3.15    3.29              9.40         69   
176          122         mpfi  3.31    3.54              8.70         92   
193          109         mpfi  3.19     3.4              9.00         88   
73           308         mpfi   3.8    3.35              8.00        184   
149          108         mpfi  3.62    2.64              7.70        111   
188          109         mpfi  3.19     3.4             10.00        100   
140          108         2bbl  3.62    2.64              8.70         73   
162           98         2bbl  3.19    3.03              9.00         70   
132          121         mpfi  3.54    3.07              9.31        110   
101          181         mpfi  3.43    3.27              9.00        152   

     peak-rpm city-mpg highway-mpg    price  
93       5200       31          37   7349.0  
176      4200       27          32  10898.0  
193      5500       25          31  12290.0  
73       4500       14          16  40960.0  
149      4800       23          23  11694.0  
188      5500       26          32   9995.0  
140      4400       26          31   7603.0  
162      4800       28          34   9258.0  
132      5250       21          28  11850.0  
101      5200       17          22  13499.0  

[10 rows x 26 columns]